name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: g++ pgprogram.cpp HTMLFile.h HTMLFile.cpp MainPage.h MainPage.cpp -o pgprogram --std=c++17
    - name: test2
      run: g++ test/test2.cpp HTMLFile.h HTMLFile.cpp -o test2 --std=c++17
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
